code --install-extension Angular.ng-template
code --install-extension EditorConfig.EditorConfig
code --install-extension HookyQR.beautify
code --install-extension Thavarajan.ionic2
code --install-extension UVBrain.Angular2
code --install-extension abusaidm.html-snippets
code --install-extension danielehrhardt.ionic3-vs-ionView-snippets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension draft-lang.draft
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.Theme-Meteor
code --install-extension idleberg.hopscotch
code --install-extension jamesmaj.easy-icons
code --install-extension jgw9617.ionic2-vscode
code --install-extension johnpapa.Angular2
code --install-extension jtlowe.vscode-icon-theme
code --install-extension loiane.ionic-extension-pack
code --install-extension mauve.terraform
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-vscode.azure-account
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension numso.prettier-standard-vscode
code --install-extension PeterJausovec.vscode-docker
code --install-extension pkosta2006.rxjs-snippets
code --install-extension robertohuertasm.vscode-icons
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension spywhere.guides
code --install-extension steoates.autoimport
code --install-extension stubailo.ignore-gitignore
code --install-extension technosophos.vscode-helm
code --install-extension tinkertrain.theme-panda
code --install-extension vscodevim.vim
code --install-extension vscoss.vscode-ansible
code --install-extension vsmobile.cordova-tools
code --install-extension zuoez02.tslint-snippets
