code --install-extension EditorConfig.EditorConfig
code --install-extension abusaidm.html-snippets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.Theme-Meteor
code --install-extension jtlowe.vscode-icon-theme
code --install-extension mauve.terraform
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-vscode.azure-account
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension numso.prettier-standard-vscode
code --install-extension PeterJausovec.vscode-docker
code --install-extension robertohuertasm.vscode-icons
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension spywhere.guides
code --install-extension steoates.autoimport
code --install-extension stubailo.ignore-gitignore
code --install-extension technosophos.vscode-helm
code --install-extension vscodevim.vim
code --install-extension vscoss.vscode-ansible
code --install-extension zuoez02.tslint-snippets
